dist: focal  # Use Ubuntu 20.04 (Focal Fossa)
language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

